apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: {{component_application}}-stage-{{epoch}}
  namespace: rhoai-tenant
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-{{hyphenized-rhoai-version}}-components-stage
  snapshot: {{component_application}}-{{epoch}}
