apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-addon-{{ocp-version}}-stage-{{epoch}}
  namespace: rhoai-tenant
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-addon-{{hyphenized-rhoai-version}}-{{ocp-version}}-fbc-stage
  snapshot: {{fbc_application}}-{{epoch}}