apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-416-1733054214
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 4bae62e203bf4e619e9e2e1ce834cfdf1d1b9950
spec:
  application: rhoai-fbc-fragment-ocp-416
  components:
    - name: rhoai-fbc-fragment-ocp-416
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:c3ba67eb57249c79367673b8aa6c90fb7864c83f7533514d807cc60873fd3544
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: ecef342382717675b03cd5ef902cec78bc7e7844