apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: {{component_application}}-prod-{{epoch}}
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: {{rbc_release_commit}}
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-{{hyphenized-rhoai-version}}-components-prod
  snapshot: __STAGE__LATEST__SNAPSHOT__
