apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: {{fbc_application}}-stage-{{epoch}}
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: {{rbc_release_commit}}
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-{{hyphenized-rhoai-version}}-{{ocp-version}}-fbc-stage
  snapshot: {{fbc_application}}-{{epoch}}