---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-operator-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-operator-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-operator-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-ml-pipelines-launcher-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-ml-pipelines-launcher-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-ml-pipelines-launcher-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-ml-pipelines-driver-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-ml-pipelines-driver-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-ml-pipelines-driver-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-kuberay-operator-controller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-kuberay-operator-controller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-kuberay-operator-controller-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-kueue-controller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-kueue-controller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-kueue-controller-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-kf-notebook-controller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-kf-notebook-controller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-kf-notebook-controller-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-data-science-pipelines-operator-controller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-data-science-pipelines-operator-controller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-data-science-pipelines-operator-controller-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-mm-rest-proxy-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-mm-rest-proxy-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-mm-rest-proxy-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-model-controller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-model-controller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-model-controller-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-modelmesh-serving-controller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-modelmesh-serving-controller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-modelmesh-serving-controller-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino      

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-codeflare-operator-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-codeflare-operator-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-codeflare-operator-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino      

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-trustyai-service-operator-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-trustyai-service-operator-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-trustyai-service-operator-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino    

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-training-operator-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-training-operator-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-training-operator-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-dashboard-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-dashboard-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-dashboard-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-data-science-pipelines-argo-workflowcontroller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-data-science-pipelines-argo-workflowcontroller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-data-science-pipelines-argo-workflowcontroller-v2-16
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino        

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-ml-pipelines-persistenceagent-v2-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-ml-pipelines-persistenceagent-v2-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-ml-pipelines-persistenceagent-v2-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-data-science-pipelines-argo-argoexec-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-data-science-pipelines-argo-argoexec-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-data-science-pipelines-argo-argoexec-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-ml-pipelines-scheduledworkflow-v2-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-ml-pipelines-scheduledworkflow-v2-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-ml-pipelines-scheduledworkflow-v2-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-modelmesh-runtime-adapter-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-modelmesh-runtime-adapter-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-modelmesh-runtime-adapter-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino 

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-notebook-controller-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-notebook-controller-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-notebook-controller-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino       

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-mlmd-grpc-server-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-mlmd-grpc-server-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-mlmd-grpc-server-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-ml-pipelines-api-server-v2-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-ml-pipelines-api-server-v2-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-ml-pipelines-api-server-v2-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-modelmesh-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-modelmesh-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-modelmesh-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino  

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-trustyai-service-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-trustyai-service-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-trustyai-service-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino        

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-model-registry-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-model-registry-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-model-registry-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino      

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-model-registry-operator-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-model-registry-operator-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-model-registry-operator-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-odh-operator-bundle-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "odh-operator-bundle-v2-16"
spec:
  image:
    name: rhoai-tenant/odh-operator-bundle-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino     
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-rhoai-v2-16-rhoai-fbc-fragment-v2-16
  namespace: rhoai-tenant
  labels:
    appstudio.redhat.com/application: "rhoai-v2-16"
    appstudio.redhat.com/component: "rhoai-fbc-fragment-v2-16"
spec:
  image:
    name: rhoai-tenant/rhoai-fbc-fragment-v2-16
    visibility: private
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino   