---
apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStreamTemplate
metadata:
  name: rhoai-template-v2-16
spec:
  project: rhoai-tenant
  variables:
    - name: version
      description: A version number for a new development stream
    - name: versionName
      description: A K8s-compliant name for the version
      defaultValue: "{{hyphenize .version}}"
    - name: branch
      description: Git repo release branch
  resources:
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Application
      metadata:
        annotations:
          application.thumbnail: "5"
        name: "rhoai-{{.versionName}}"
      spec:
        displayName: "rhoai-{{.versionName}}"
    # - apiVersion: appstudio.redhat.com/v1alpha1
    #   kind: Component
    #   metadata:
    #     annotations:
    #       build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    #     name: odh-operator-{{.versionName}}
    #   spec:
    #     application: "rhoai-{{.versionName}}"
    #     build-nudges-ref:
    #     - "rhoai-fbc-fragment-{{.versionName}}"
    #     componentName: odh-operator-{{.versionName}}
    #     source:
    #       git:
    #         dockerfileUrl: bundle/Dockerfile
    #         revision: "{{.branch}}"
    #         url: https://github.com/rhoai-rhtap/RHOAI-Build-Config
    # - apiVersion: appstudio.redhat.com/v1alpha1
    #   kind: Component
    #   metadata:
    #     annotations:
    #       build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    #     name: "odh-operator-{{.versionName}}"
    #   spec:
    #     application: "rhoai-{{.versionName}}"
    #     build-nudges-ref:
    #     - odh-operator-{{.versionName}}
    #     componentName: "odh-operator-{{.versionName}}"
    #     source:
    #       git:
    #         dockerfileUrl: Dockerfiles/Dockerfile
    #         revision: "{{.branch}}"
    #         url: https://github.com/rhoai-rhtap/rhods-operator
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-ml-pipelines-launcher-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-ml-pipelines-launcher-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: backend/Dockerfile.konflux.launcher
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/data-science-pipelines.git 
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-ml-pipelines-driver-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-ml-pipelines-driver-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: backend/Dockerfile.konflux.driver
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/data-science-pipelines.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-kuberay-operator-controller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-kuberay-operator-controller-{{.versionName}}"
        source:
          git:
            context: ./ray-operator/
            dockerfileUrl: ./ray-operator/Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/kuberay.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-kueue-controller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-kueue-controller-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/kueue.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-kf-notebook-controller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-kf-notebook-controller-{{.versionName}}"
        source:
          git:
            context: ./components/
            dockerfileUrl: notebook-controller/Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/kubeflow.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-data-science-pipelines-operator-controller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-data-science-pipelines-operator-controller-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/data-science-pipelines-operator.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-mm-rest-proxy-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-mm-rest-proxy-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/rest-proxy.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-model-controller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-model-controller-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/odh-model-controller.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-modelmesh-serving-controller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-modelmesh-serving-controller-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/modelmesh-serving.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-codeflare-operator-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-codeflare-operator-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/codeflare-operator.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-trustyai-service-operator-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-trustyai-service-operator-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/trustyai-service-operator.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-training-operator-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-training-operator-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: build/images/training-operator/Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/training-operator.git 
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-dashboard-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-dashboard-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/odh-dashboard.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-data-science-pipelines-argo-workflowcontroller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-data-science-pipelines-argo-workflowcontroller-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: argo-workflowcontroller/Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/rhoai-rhtap/argo-workflows.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-ml-pipelines-persistenceagent-v2-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-ml-pipelines-persistenceagent-v2-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: backend/Dockerfile.konflux.persistenceagent
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/data-science-pipelines.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-data-science-pipelines-argo-argoexec-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-data-science-pipelines-argo-argoexec-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: argo-argoexec/Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/argo-workflows.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-ml-pipelines-scheduledworkflow-v2{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-ml-pipelines-scheduledworkflow-v2{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: backend/Dockerfile.konflux.scheduledworkflow
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/data-science-pipelines.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-modelmesh-runtime-adapter-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-modelmesh-runtime-adapter-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-notebook-controller-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-notebook-controller-{{.versionName}}"
        source:
          git:
            context: ./components/
            dockerfileUrl: odh-notebook-controller/Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/kubeflow.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-mlmd-grpc-server-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-mlmd-grpc-server-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: ml_metadata/tools/docker_server/Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/ml-metadata.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-ml-pipelines-api-server-v2-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-ml-pipelines-api-server-v2-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: backend/Dockerfile.konflux.api
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/data-science-pipelines.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-modelmesh-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-modelmesh-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/modelmesh.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-trustyai-service-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-trustyai-service-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/trustyai-explainability.git
    # - apiVersion: appstudio.redhat.com/v1alpha1
    #   kind: Component
    #   metadata:
    #     annotations:
    #       build.appstudio.openshift.io/pipeline: '{"name":"fbc-builder","bundle":"latest"}'
    #     name: "rhoai-fbc-fragment-{{.versionName}}"
    #   spec:
    #     application: "rhoai-{{.versionName}}"
    #     componentName: "rhoai-fbc-fragment-{{.versionName}}"
    #     source:
    #       git:
    #         context: catalog/v4.13
    #         dockerfileUrl: Dockerfile
    #         revision: "{{.branch}}"
    #         url: https://github.com/rhoai-rhtap/RHOAI-Build-Config
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-model-registry-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-model-registry-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/model-registry.git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        name: "odh-model-registry-operator-{{.versionName}}"
      spec:
        application: "rhoai-{{.versionName}}"
        build-nudges-ref:
        - odh-operator-{{.versionName}}
        componentName: "odh-model-registry-{{.versionName}}"
        source:
          git:
            context: ./
            dockerfileUrl: Dockerfile.konflux
            revision: "{{.branch}}"
            url: https://github.com/red-hat-data-services/model-registry-operator.git
---
apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: rhoai-stream-v2-16
spec:
  project: rhoai-tenant
  template:
    name: rhoai-template-v2-16
    values:
      - name: version
        value: "v2.16"
      - name: branch
        value: "rhoai-2.16"
