name: Enforce Stricter Branch Protection

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to apply stricter protection'
        required: true
        type: string

jobs:
  apply-protection-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Read Repository URLs
      id: read-repos
      run: |
        REPO_FILE="repos.txt"
        repository_urls=()
        while IFS= read -r line; do
          repository_urls+=("$line")
        done < "$REPO_FILE"
        echo "repository_urls=${repository_urls[*]}" >> $GITHUB_ENV

    - name: Check Branch Existence and Apply Protection Rules
      env:
        RULESET_TOKEN: ${{ secrets.RULESET_GIT }}
      run: |
        IFS=' ' read -r -a urls <<< "$repository_urls"
        for repo_url in "${urls[@]}"; do
          repo_name=$(basename "$repo_url" .git)
          echo "Processing repository: ${repo_name}"

          # Construct API URL for checking the branch
          branch_check_url="https://api.github.com/repos/DevOps-automation-tasks/$repo_name/branches/${{ github.event.inputs.branch_name }}"
          
          # Check if the branch exists
          branch_check_response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $RULESET_TOKEN" "$branch_check_url")
          if [ "$branch_check_response" -ne 200 ]; then
            echo "Branch ${{ github.event.inputs.branch_name }} does not exist in ${repo_name}. Exiting."
            exit 1
          fi
          
          echo "Branch ${{ github.event.inputs.branch_name }} exists in ${repo_name}."

          # Construct API URL for applying protection rules
          api_url="https://api.github.com/repos/DevOps-automation-tasks/$repo_name/branches/${{ github.event.inputs.branch_name }}/protection"
          echo "API URL: $api_url"

          # Apply stricter protection rules
          curl -X PUT -H "Authorization: token $RULESET_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               -d '{
                 "required_status_checks": {
                   "strict": true,
                   "contexts": []
                 },
                 "enforce_admins": true,
                 "required_pull_request_reviews": {
                   "dismiss_stale_reviews": true,
                   "require_code_owner_reviews": true,
                   "required_approving_review_count": 2
                 },
                 "restrictions": {
                   "users": ["devops-bot"],
                   "teams": ["devops-team"]
                 },
                 "required_linear_history": true,
                 "allow_force_pushes": false,
                 "allow_deletions": false
               }' \
               "$api_url" || { echo "Failed to apply stricter protection rules for ${repo_name}"; exit 1; }
        done
