name: Insta Merge FBC Nudges

on:
  pull_request:
    branches:
      - 'rhoai-*'  # Trigger the workflow on pushes to any rhoai-* branch
    types:
      - opened
      - reopened
    paths:
      - catalog/catalog-patch.yaml
      - schedule/catalog-scheduled-trigger.txt

env:
  COMPONENT: odh-operator-bundle

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  insta-merge:
    if: ${{ github.event.sender.login == 'konflux-internal-p02[bot]'  && startsWith(github.event.pull_request.title, 'Update odh-operator-bundle') }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.RHOAI_DEVOPS_APP_ID }}
          private_key: ${{ secrets.RHOAI_DEVOPS_APP_PRIVATE_KEY }}
      - name: instant-merge
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # Declare variables
          BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          VERSION=v${BRANCH/rhoai-/}
          SUFFIX=${VERSION/./-}
          REGEX="^Update $COMPONENT-$SUFFIX to [0-9a-z]{1,40}$"
          
          #Check if PR title is as per the convention
          if [[ "${{ github.event.pull_request.title }}" =~ $REGEX ]]
          then
            gh pr merge --merge --admin ${{ github.event.pull_request.html_url }}
            echo "Merged!!"
          else
            echo "Insta-merge not configured to merge this PR, skipping."
          fi
